//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wpfppp.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memberships
    {
        public int MembershipID { get; set; }
        public int MemberID { get; set; }
        public int ClubID { get; set; }
        public System.DateTime JoinDate { get; set; }
    
        public virtual Clubs Clubs { get; set; }
        public virtual Members Members { get; set; }
    }
}
